name: "Publish Documentation to NIST Pages"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # - uses: usnistgov/Docs4NIST@0.7
      - uses: martintb/Docs4NIST@themedir-bug
        with:
          docs-folder: docs/
          pip-requirements: "requirements_sphinx820.txt"

